# Generated by Django 4.2.4 on 2023-08-13 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_is_mobile_verified_user_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
