# Generated by Django 4.2.4 on 2023-08-08 03:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("regions", "0004_city_region_code_district_province_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference_number",
                    models.IntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(6),
                            django.core.validators.MaxLengthValidator(12),
                        ],
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TCH", "Teacher"),
                            ("NTP", "Non-teaching Personnel"),
                            ("STU", "Student"),
                        ],
                        default="STU",
                        max_length=3,
                    ),
                ),
                ("level", models.CharField(max_length=32)),
                ("created_datetime", models.DateTimeField(auto_now_add=True)),
                ("updated_datetime", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(1),
                            django.core.validators.MaxLengthValidator(3),
                        ]
                    ),
                ),
                ("school", models.CharField(max_length=255)),
                ("street_address", models.CharField(max_length=255)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.city",
                        to_field="code",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.district",
                        to_field="code",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.province",
                        to_field="code",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regions.region",
                        to_field="code",
                    ),
                ),
            ],
        ),
    ]
