# Generated by Django 4.2.3 on 2023-07-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0002_remove_city_province_remove_district_city_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="province",
            name="region_code",
            field=models.ForeignKey(
                default="0800000000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.region",
                to_field="code",
            ),
        ),
    ]
