# Generated by Django 4.2.3 on 2023-07-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regions", "0003_region_province_region_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="region_code",
            field=models.ForeignKey(
                default="0800000000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.region",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="province_code",
            field=models.ForeignKey(
                default="0831600000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.province",
                to_field="code",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region_code",
            field=models.ForeignKey(
                default="0800000000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.region",
                to_field="code",
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="city_code",
            field=models.ForeignKey(
                default="0831600000",
                on_delete=django.db.models.deletion.CASCADE,
                to="regions.city",
                to_field="code",
            ),
        ),
    ]
